import QtQuick 6.7

QtObject {
    readonly property string name: "Night City 2077"
    readonly property bool supporterOnly: false
    readonly property bool terminalMode: false
    readonly property bool classicMode: false
    readonly property bool iconGlyphsVisible: true
    readonly property string iconFolder: "icons-carbon"
    readonly property bool iconColorize: true
    readonly property color iconTint: "#5ef6ff"
    readonly property string uiFontFile: "fonts/night-city-2077/Rajdhani-Medium.ttf"
    readonly property string displayFontFile: "fonts/night-city-2077/Rajdhani-Bold.ttf"
    readonly property string monoFontFile: "fonts/night-city-2077/Rajdhani-Regular.ttf"

    // Optional capabilities consumed generically by shared UI components.
    readonly property string backdropComponentFile: "../themes/nightcity/NightCityBackdrop.qml"
    readonly property string foregroundComponentFile: "../themes/nightcity/NightCityForeground.qml"
    readonly property string pageTransitionComponentFile: "../themes/nightcity/NightCityPageTransition.qml"
    readonly property bool equipmentAccentsEnabled: false
    readonly property bool ambientScanEnabled: true
    readonly property bool controlSignalEnabled: true
    readonly property bool navSignalEnabled: true
    readonly property bool panelLocatorEnabled: false
    readonly property bool headerSignalEnabled: true
    readonly property bool angularControlsEnabled: true
    readonly property real angularCutSize: 9.0
    readonly property real angularNotchSize: 5.0
    readonly property real angularPanelCutSize: 14.0
    readonly property real angularStrokeWidth: 1.15
    readonly property bool glitchInteractionsEnabled: true
    readonly property real glitchIntensity: 1.0
    readonly property bool diagnosticEasterEggsEnabled: true
    readonly property bool technicalTypographyEnabled: true
    readonly property bool floatingPanelsEnabled: true
    readonly property bool glyphRailsEnabled: true
    readonly property string logoDialFile: "themes/night-city-2077/night-city-logo-dial.svg"
    readonly property real logoDialOpacity: 0.88
    readonly property bool logoColorize: true
    readonly property color logoTint: "#f75049"
    readonly property color signalPrimary: "#f75049"
    readonly property color signalSecondary: "#5ef6ff"
    readonly property color signalDanger: "#ff3155"
    readonly property color signalSuccess: "#1ded83"
    readonly property color signalOff: "#3d5e2630"
    readonly property color transitionSweep: "#f75049"
    readonly property color transitionTrail: "#5ef6ff"
    readonly property real interactionSweepDuration: 180
    readonly property real interactionSweepWidth: 0.22
    readonly property real pageTransitionDuration: 420
    readonly property real locatorOpacity: 0.92

    readonly property color backgroundA: "#0e0e17"
    readonly property color backgroundB: "#08080f"
    readonly property color backgroundC: "#171019"

    readonly property color surface: "#d60e0e17"
    readonly property color surfaceSoft: "#b8090910"
    readonly property color surfaceStrong: "#df14141e"
    readonly property color surfaceRaised: "#e61a1822"
    readonly property color surfaceTop: "#dc16131d"
    readonly property color surfaceBottom: "#e2090911"
    readonly property color surfaceStrongTop: "#e71d1823"
    readonly property color surfaceStrongBottom: "#e50c0c14"

    readonly property color border: "#98f75049"
    readonly property color borderSoft: "#58f75049"
    readonly property color borderStrong: "#e8f75049"
    readonly property color divider: "#50f75049"
    readonly property color text: "#ffffff"
    readonly property color muted: "#d6d0d0"
    readonly property color subtle: "#aaa1a8"
    readonly property color faint: "#776e77"

    readonly property color primary: "#f75049"
    readonly property color primaryBright: "#ff6b63"
    readonly property color primaryHot: "#5ef6ff"
    readonly property color primaryDeep: "#6f1d26"
    readonly property color primarySoft: "#38f75049"
    readonly property color hover: "#28f75049"
    readonly property color success: "#1ded83"
    readonly property color warning: "#f0b537"
    readonly property color danger: "#ff3155"
    readonly property color updateAlertSurface: danger
    readonly property color updateAlertText: primaryText
    readonly property color classificationHandmade: "#ff9fce"
    readonly property color classificationToolmade: "#8fd8ff"
    readonly property color consoleBackground: "#f2090911"
    readonly property color shadow: "#d9000000"
    readonly property color innerHighlight: "#225ef6ff"
    readonly property color focusColor: "#5ef6ff"
    readonly property color primaryText: "#0e0e17"

    readonly property color appBorder: "#d9f75049"
    readonly property color titleBarSurface: "#f20a0a12"
    readonly property color titleBarButtonHover: "#3df75049"
    readonly property color titleBarCloseHover: "#f0f75049"
    readonly property color logoCapsuleSurface: "#d90e0e17"

    readonly property color panelTop: "#d917131d"
    readonly property color panelMiddle: "#d5121019"
    readonly property color panelBottom: "#e0090911"
    readonly property color panelSoftTop: "#bc13111a"
    readonly property color panelSoftMiddle: "#b40c0c14"
    readonly property color panelSoftBottom: "#c408080f"
    readonly property color panelStrongTop: "#e51d1823"
    readonly property color panelStrongMiddle: "#df16121d"
    readonly property color panelStrongBottom: "#e20a0a12"
    readonly property color panelTopHighlight: "#285ef6ff"
    readonly property color panelInnerBorder: "#64f75049"
    readonly property color panelStrongInnerBorder: "#bff75049"
    readonly property color panelOverlay: "#0ff75049"
    readonly property color panelStrongOverlay: "#18f75049"
    readonly property color panelGlowShadow: "#66f75049"
    readonly property color panelConvexLeftHighlight: "#205ef6ff"
    readonly property color panelConvexRightShadow: "#68000000"
    readonly property color panelConvexBottomShadow: "#76000000"
    readonly property color panelConvexCenterGlow: "#08000000"
    readonly property real panelNoiseSoftOpacity: 0.0
    readonly property real panelNoiseOpacity: 0.0
    readonly property real panelNoiseStrongOpacity: 0.0
    readonly property real panelHighlightSoftOpacity: 0.08
    readonly property real panelHighlightOpacity: 0.10
    readonly property real panelHighlightStrongOpacity: 0.14
    readonly property real panelOverlaySoftOpacity: 0.10
    readonly property real panelOverlayOpacity: 0.16

    readonly property color primaryButtonBorder: "#d9f75049"
    readonly property color primaryButtonHoverBorder: "#5ef6ff"
    readonly property color primaryButtonTop: "#351319"
    readonly property color primaryButtonMiddle: "#251017"
    readonly property color primaryButtonBottom: "#160c14"
    readonly property color primaryButtonHoverTop: "#f75049"
    readonly property color primaryButtonHoverMiddle: "#e74443"
    readonly property color primaryButtonHoverBottom: "#bd3038"
    readonly property color primaryButtonShadow: "#78000000"
    readonly property color primaryButtonHoverShadow: "#70f75049"
    readonly property color primaryButtonSheenTransparent: "#00ffffff"
    readonly property color primaryButtonSheen: "#205ef6ff"
    readonly property color primaryButtonLip: "#6f1d26"
    readonly property color primaryButtonLipPressed: "#43222f"
    readonly property color primaryButtonGlassTop: "#125ef6ff"
    readonly property color primaryButtonGlassMiddle: "#08f75049"
    readonly property color primaryButtonInnerShadow: "#6b000000"
    readonly property string primaryButtonTextureFile: ""
    readonly property real primaryButtonTextureOpacity: 0.0
    readonly property string primaryButtonLensOverlayFile: "themes/night-city-2077/night-city-button-signal.svg"
    readonly property real primaryButtonLensOverlayOpacity: 0.92
    readonly property color primaryButtonText: "#ffffff"
    readonly property real buttonGlassBackdropOpacity: 0.0
    readonly property real buttonGlassBackdropBlur: 0.0
    readonly property int buttonGlassBackdropBlurMax: 20
    readonly property real buttonGlassBackdropBlurMultiplier: 0.0
    readonly property real buttonGlassBackdropBrightness: 0.0
    readonly property real buttonGlassBackdropContrast: 0.0
    readonly property real buttonGlassBackdropSaturation: 1.0
    readonly property real buttonGlassBackdropDownsample: 0.92
    readonly property real buttonGlassLensOpacity: 0.0
    readonly property real buttonGlassLensInsetX: 0.08
    readonly property real buttonGlassLensInsetY: 0.18
    readonly property real buttonGlassLensOffsetX: 0.0
    readonly property real buttonGlassLensOffsetY: -0.02
    readonly property real buttonGlassLensBlur: 0.0
    readonly property real buttonGlassLensContrast: 0.0
    readonly property real buttonGlassLensSaturation: 1.0
    readonly property color buttonGlassLensLeftHighlight: "#005ef6ff"
    readonly property color buttonGlassLensCenterHighlight: "#00f75049"
    readonly property color buttonGlassLensRightShadow: "#00000000"

    readonly property color ghostSurface: "#e80e0e17"
    readonly property color ghostHoverSurface: "#4af75049"
    readonly property color ghostPressedSurface: "#d9f75049"
    readonly property color ghostShadow: "#70000000"

    readonly property color fieldSurface: "#f00b0b13"
    readonly property color fieldHoverSurface: "#f317121b"
    readonly property color fieldFocusSurface: "#f31a1822"
    readonly property color comboSurfaceOpen: "#f21a1822"
    readonly property color comboHoverSurface: "#38f75049"
    readonly property color comboPopupSurface: "#fb0b0b13"
    readonly property color comboHighlight: "#f75049"

    readonly property color checkboxSurface: "#421d1721"
    readonly property color checkboxHoverSurface: "#70f75049"
    readonly property color checkboxCheckedSurface: "#f75049"
    readonly property color switchTrackOff: "#6b483b45"
    readonly property color sliderTrack: "#7a5b4149"

    readonly property color navHoverSurface: "#32f75049"
    readonly property color navActiveGlow: "#805ef6ff"
    readonly property color navActiveTop: "#f75049"
    readonly property color navActiveMiddle: "#e74443"
    readonly property color navActiveBottom: "#a72a35"

    readonly property color rowHover: "#32f75049"
    readonly property color rowSelectedSurface: "#54f75049"
    readonly property color previewSurface: "#16151d"
    readonly property color previewSurfaceSoft: "#0d0d15"

    readonly property color helpCategorySelected: "#f75049"
    readonly property color helpCategoryHover: "#38f75049"
    readonly property color helpCategorySurface: "#e80e0e17"
    readonly property color helpBadgeSelected: "#5ef6ff"
    readonly property color helpBadge: "#245ef6ff"
    readonly property color helpBadgeBorder: "#a85ef6ff"
    readonly property color helpTopicSelected: "#f75049"
    readonly property color helpTopicHover: "#32f75049"
    readonly property color helpTopicSurface: "#e80e0e17"
    readonly property color stepBadge: "#305ef6ff"
    readonly property color richAccent: "#5ef6ff"

    readonly property color backdropOverlayTop: "#100e0e17"
    readonly property color backdropOverlayMiddle: "#240e0e17"
    readonly property color backdropOverlayBottom: "#6b08080f"

    readonly property string backdropBaseFile: "themes/night-city-2077/night-city-backdrop.svg"
    readonly property string backdropBranchTopFile: ""
    readonly property string backdropBranchBottomFile: ""
    readonly property string backdropPetalFile: ""
    readonly property string panelNoiseFile: ""
    readonly property string panelGlintFile: ""
    readonly property string panelRefractionFile: ""
    readonly property real panelRefractionOpacity: 0.0
    readonly property string panelEdgeFile: "themes/night-city-2077/night-city-panel-frame.svg"
    readonly property real panelEdgeOpacity: 0.90
    readonly property bool customFrameExclusive: true
    readonly property real customFrameRadius: 0.0
    readonly property string goldTrimFile: "themes/night-city-2077/night-city-data-rail.svg"
    readonly property real goldTrimOpacity: 0.74
    readonly property bool glassBackdropEnabled: false
    readonly property real glassBackdropOpacity: 0.0
    readonly property real glassBackdropBlur: 0.0
    readonly property int glassBackdropBlurMax: 28
    readonly property real glassBackdropBlurMultiplier: 0.0
    readonly property real glassBackdropBrightness: 0.0
    readonly property real glassBackdropContrast: 0.0
    readonly property real glassBackdropSaturation: 1.0
    readonly property real glassBackdropDownsample: 0.90
    readonly property string logoFile: "kfps-logo.png"
    readonly property bool backdropBranchesVisible: false
    readonly property bool backdropPetalsVisible: false
    readonly property real backdropTopBranchOpacity: 0.0
    readonly property real backdropBottomBranchOpacity: 0.0
    readonly property real sidebarBranchOpacity: 0.0
    readonly property real sidebarCompactBranchOpacity: 0.0
    readonly property bool supporterSignatureVisible: false
    readonly property string supporterSignatureText: ""
}
