import type { ThemeDefinition } from "./types";

const fonts = {
  "--ts-font-heading": "'Space Grotesk', system-ui, -apple-system, sans-serif",
  "--ts-font-body": "'Inter', system-ui, -apple-system, sans-serif",
  "--ts-font-mono": "'IBM Plex Mono', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
};

export const themes: Record<ThemeDefinition["id"], ThemeDefinition> = {
  porsche: {
    id: "porsche",
    label: "Porsche",
    description: "Clean. Precise. Understated.",
    vars: {
      ...fonts,
      "--ts-bg": "#0c0c0c",
      "--ts-surface": "#121212",
      "--ts-card": "#1a1a1a",
      "--ts-border": "#2a2a2a",
      "--ts-text": "#ffffff",
      "--ts-muted": "#a3a3a3",
      "--ts-dim": "#737373",
      "--ts-accent": "#E32929",
      "--ts-accent-soft": "rgba(227, 41, 41, 0.10)",
      "--ts-accent-border": "rgba(227, 41, 41, 0.45)",
      "--ts-success": "#34d399",
      "--ts-warning": "#fbbf24",
      "--ts-danger": "#f87171",
      "--ts-heading-tracking": "-0.04em",
      "--ts-heading-tracking-lg": "-0.045em",
      "--ts-heading-weight": "600",
      "--ts-body-leading": "1.65",
      "--ts-card-padding": "20px",
      "--ts-section-gap": "24px",
      "--ts-radius-sm": "12px",
      "--ts-radius-md": "16px",
      "--ts-radius-lg": "24px",
      "--ts-radius-pill": "16px",
      "--ts-button-radius": "24px",
      "--ts-shadow-card": "0 25px 50px -12px rgb(0 0 0 / 0.45)",
      "--ts-glow": "none",
      "--ts-data-size": "3.75rem",
      "--ts-data-tracking": "-0.04em",
      "--ts-photo-overlay": "linear-gradient(to top, rgba(0,0,0,0.92) 0%, transparent 55%)",
      "--ts-photo-brightness": "1",
      "--ts-photo-contrast": "1",
      "--ts-photo-saturate": "1",
      "--ts-cta-bg": "#ffffff",
      "--ts-cta-text": "#000000",
      "--ts-cta-border": "transparent",
      "--ts-label-tracking": "0.08em",
    },
  },
  ferrari: {
    id: "ferrari",
    label: "Ferrari",
    description: "Bold. Dramatic. Passionate.",
    vars: {
      ...fonts,
      "--ts-bg": "#0a0a0a",
      "--ts-surface": "#111111",
      "--ts-card": "#181818",
      "--ts-border": "#252525",
      "--ts-text": "#ffffff",
      "--ts-muted": "#a3a3a3",
      "--ts-dim": "#737373",
      "--ts-accent": "#FF2800",
      "--ts-accent-soft": "rgba(255, 40, 0, 0.20)",
      "--ts-accent-border": "rgba(255, 40, 0, 0.55)",
      "--ts-success": "#34d399",
      "--ts-warning": "#fbbf24",
      "--ts-danger": "#f87171",
      "--ts-heading-tracking": "-0.03em",
      "--ts-heading-tracking-lg": "-0.05em",
      "--ts-heading-weight": "600",
      "--ts-body-leading": "1.55",
      "--ts-card-padding": "20px",
      "--ts-section-gap": "20px",
      "--ts-radius-sm": "12px",
      "--ts-radius-md": "16px",
      "--ts-radius-lg": "24px",
      "--ts-radius-pill": "16px",
      "--ts-button-radius": "24px",
      "--ts-shadow-card": "0 25px 50px -12px rgb(0 0 0 / 0.55)",
      "--ts-glow": "0 0 32px rgba(255, 40, 0, 0.18)",
      "--ts-data-size": "3.75rem",
      "--ts-data-tracking": "-0.04em",
      "--ts-photo-overlay": "linear-gradient(to top, rgba(0,0,0,0.92) 0%, transparent 55%)",
      "--ts-photo-brightness": "0.92",
      "--ts-photo-contrast": "1.05",
      "--ts-photo-saturate": "1.05",
      "--ts-cta-bg": "#FF2800",
      "--ts-cta-text": "#ffffff",
      "--ts-cta-border": "transparent",
      "--ts-label-tracking": "0.08em",
    },
  },
};

export const DEFAULT_THEME: ThemeDefinition["id"] = "porsche";
